server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: true
    default-schema: public
    change-log: classpath:db/changelog_init.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: create
cbr:
  daily: https://www.cbr.ru/scripts/XML_daily.asp
